class samba::service (
  $workgroup = "$samba::params::workgroup",
  $server_string = "$samba::params::server_string",
  $netbios_name = "$samba::params::netbios_name",
  $interfaces = "$samba::params::interfaces",
  $hosts_allow = "$samba::params::hosts_allow",
  # Logging Options
  $log_file = "$samba::params::log_file",
  $max_log_size = "$samba::params::max_log_size",
  # Security Options
  $security = "$samba::params::security",
  $passdb_backend = "$samba::params::passdb_backend",
  $realm = "$samba::params::realm",
  $password_server = "$samba::params::password_server",
  # Domain Controller
  $domain_master = "$samba::params::domain_master",
  $domain_logons = "$samba::params::domain_logons",
  $logon_script = "$samba::params::logon_script",
  $add_user_script = "$samba::params::add_user_script",
  $add_group_script = "$samba::params::add_groupscript",
  $add_machine_script = "$samba::params::add_machine_script",
  $delete_user_script = "$samba::params::delete_user_script",
  $delete_group_script = "$samba::params::delete_group_script",
  $delete_user_from_group_script = "$samba::params::delete_user_from_groupscript",
  $delete_machine_script = "$samba::params::delete_machine_script",
  # Browser Control
  $local_master = "$samba::params::local_master",
  $os_level = "$samba::params::os_level",
  $preferred_master = "$samba::params::preferred_master",
  # Name Resolution
  $wins_support = "$samba::params::wins_support",
  $wins_server = "$samba::params::wins_server",
  $wins_proxy = "$samba::params::wins_proxy",
  $dns_proxy = "$samba::params::dns_proxy",
  # Printing Options
  $load_printers = "$samba::params::load_printers",
  $cups_options = "$samba::params::cups_options",
  $printcap_name = "$samba::params::printcap_name",
  $printing = "$samba::params::printing",
  # Filesystem Options
  $map_archive = "$samba::params::map_archive",
  $map_hidden = "$samba::params::map_hidden",
  $map_read_only = "$samba::params::map_read_only",
  $map_system = "$samba::params::map_system",
  $store_dos_attributes = "$samba::params::store_dos_attributes"
) inherits samba::params {
  service { "$samba::params::service_name":
    ensure  => "$samba::params::ensure",
    enable  => true,
  }
  file { '/etc/samba/smb.conf':
    ensure  => present,
    owner   => 'root',
    group   => 'root',
    content => template("${module_name}/smb.conf.erb"),
    notify  => Service["$samba::params::service_name"],
  }
}
